### ISSUE TITLE
Serializing the model

### ISSUE THREAD

**Issue by TravisBarryDick** [innerlee/LIBLINEAR.jl#1]
Hey, thanks for making a wrapper for liblinear! It's awesome. I am trying to use it in a distributed setting, and it would be awesome if you could implement a method for serializing the LinearModel{T} class.

**Comment by innerlee** [comment]
thanks for the good suggestion!

**Comment by innerlee** [comment]
Could you share your thoughts on this? And more information about the `distributed setting'. Thanks!

**Comment by innerlee** [comment]
#8 
achieve this.
