### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by rssdev10** [innerlee/LIBLINEAR.jl#25]
Hello, I tried to rebuild and update liblinear_jll.jl to the latest version of the liblinear 2.45 with Mac M1 support. I prepared a patch https://github.com/rssdev10/Yggdrasil/commit/0053178f3635bfc1c9ef147c837712e53f6dcc13 and deployed all the binaries [liblinear_jll.jl](https://github.com/rssdev10/liblinear_jll.jl). But, API a little bit changed compared with 2.30.

E.g. [struct model](https://github.com/cjlin1/liblinear/blame/master/linear.h#L44) got a new field `double rho; /* one-class SVM only */` . The method `check_parameter` gives an error `Initial-solution specification supported only for solvers L2R_LR, L2R_L2LOSS_SVC, and L2R_L2LOSS_SVR`. Maybe something other was also changed, but I'm not familiar with `liblinear`.

Who can help in aligning the julia-wrapper for the new binaries?

**Comment by ericphanson** [comment]
I've updated the wrapper in #26

**Comment by ericphanson** [comment]
maybe this should stay open until that gets merged? (hopefully soon, but I think it would depend on the maintainer's review bandwidth)
