### ISSUE TITLE
transfer to JuliaML?

### ISSUE THREAD

**Issue by ericphanson** [innerlee/LIBLINEAR.jl#27]
If you are open to it @innerlee I think it could make sense to transfer the repo to JuliaML (where LIBSVM.jl is) so there are more folks with access to it to help maintain it. (You would still have admin rights to the repo itself). If you are up for I am sure I can find a JuliaML member to help transfer.

**Comment by barucden** [comment]
It would be great if we managed to transfer the repository so that we have more maintainers.

**Comment by barucden** [comment]
Thank you, @innerlee, for pushing this forward. The transfer to JuliaML brought many maintainers to the repo.
