### ISSUE TITLE
Minimum supported Julia version

### ISSUE THREAD

**Issue by barucden** [innerlee/LIBLINEAR.jl#30]
The current CI runs tests for Julia 1.3, for which the dependencies cannot be satisfied due to `liblinear_jll 2.47` requiring at least Julia 1.6:
```
 ERROR: LoadError: Unsatisfiable requirements detected for package liblinear_jll [275f1f90]:
 liblinear_jll [275f1f90] log:
 ├─possible versions are: [2.30.0, 2.47.0] or uninstalled
 ├─restricted to versions 2.47 by an explicit requirement, leaving only versions 2.47.0
 └─restricted by julia compatibility requirements to versions: 2.30.0 or uninstalled — no versions left
```

Do we need to support (and run tests for) Julia 1.3? The current LTS version is 1.6.7.

(CC @ericphanson @ablaom)

**Comment by ericphanson** [comment]
Ah, let’s bump to 1.6 then

**Comment by barucden** [comment]
MLJ.jl is also at 1.6:

https://github.com/alan-turing-institute/MLJ.jl/blob/6f46257f14bf8ffc8d22612c1e448be6ff92364e/Project.toml#L52

Let's wait for confirmation from Anthony.

**Comment by ablaom** [comment]
Yeah, I vote for the bump to 1.6. But note we still need #34 before tagging a new release, unless someone has done it already.
